from __future__ import annotations

from typing import Dict, List

from synthetic.models import PersonaCode


PERSONAS: Dict[PersonaCode, dict] = {
    "EXCELLENT_PROFILE": {
        "user": {
            "user_id": "user_001",
            "full_name": "Ava Thompson",
            "age": 41,
            "city": "Austin",
            "state": "TX",
            "occupation": "Product Director",
            "annual_income": 168000,
        },
        "report": {
            "bureau": "TransUnion",
            "score": 792,
            "score_change_30d": 6,
            "summary": "Long credit history, very low utilization, and spotless payment behavior support an excellent profile.",
            "score_factors": [
                "Low revolving utilization across multiple cards",
                "No missed payments or derogatory marks",
                "Long average account age and healthy credit mix",
            ],
        },
        "credit_accounts": [
            {
                "issuer": "Chase",
                "product_name": "Sapphire Preferred",
                "account_type": "credit_card",
                "status": "open",
                "opened_date": "2016-04-12",
                "credit_limit": 18000,
                "current_balance": 620,
                "apr": 19.99,
                "autopay_enabled": True,
                "payment_status": "on_time",
            },
            {
                "issuer": "Amex",
                "product_name": "Blue Cash Preferred",
                "account_type": "credit_card",
                "status": "open",
                "opened_date": "2018-09-01",
                "credit_limit": 14000,
                "current_balance": 540,
                "apr": 18.24,
                "autopay_enabled": True,
                "payment_status": "on_time",
            },
            {
                "issuer": "Citi",
                "product_name": "Double Cash",
                "account_type": "credit_card",
                "status": "open",
                "opened_date": "2020-06-15",
                "credit_limit": 12000,
                "current_balance": 310,
                "apr": 17.49,
                "autopay_enabled": True,
                "payment_status": "on_time",
            },
        ],
        "loan_accounts": [
            {
                "lender": "Wells Fargo",
                "product_name": "Auto Loan",
                "account_type": "auto_loan",
                "status": "open",
                "opened_date": "2022-03-10",
                "original_balance": 32000,
                "current_balance": 16800,
                "monthly_payment": 540,
                "interest_rate": 4.1,
                "payment_status": "on_time",
            },
            {
                "lender": "Rocket Mortgage",
                "product_name": "30 Year Fixed",
                "account_type": "mortgage",
                "status": "open",
                "opened_date": "2019-07-01",
                "original_balance": 410000,
                "current_balance": 342000,
                "monthly_payment": 2480,
                "interest_rate": 3.4,
                "payment_status": "on_time",
            },
        ],
        "inquiries": [
            {
                "creditor": "Wells Fargo Auto",
                "inquiry_type": "auto",
                "inquiry_date": "2022-03-05",
                "bureau": "TransUnion",
                "is_hard": True,
            }
        ],
        "payment_history_statuses": ["on_time"] * 6,
    },
    "HIGH_UTILIZATION_USER": {
        "user": {
            "user_id": "user_002",
            "full_name": "Marcus Lee",
            "age": 33,
            "city": "Phoenix",
            "state": "AZ",
            "occupation": "Operations Manager",
            "annual_income": 84000,
        },
        "report": {
            "bureau": "Experian",
            "score": 648,
            "score_change_30d": -24,
            "summary": "The profile is held back by high revolving balances even though payment history is otherwise mostly solid.",
            "score_factors": [
                "Revolving balances are using most available credit",
                "Recent balance growth pushed utilization sharply higher",
                "Payment history remains strong, limiting further damage",
            ],
        },
        "credit_accounts": [
            {
                "issuer": "Capital One",
                "product_name": "Quicksilver",
                "account_type": "credit_card",
                "status": "open",
                "opened_date": "2019-05-20",
                "credit_limit": 4500,
                "current_balance": 4180,
                "apr": 26.15,
                "autopay_enabled": False,
                "payment_status": "on_time",
            },
            {
                "issuer": "Discover",
                "product_name": "It Cash Back",
                "account_type": "credit_card",
                "status": "open",
                "opened_date": "2021-02-11",
                "credit_limit": 3200,
                "current_balance": 2810,
                "apr": 24.74,
                "autopay_enabled": False,
                "payment_status": "on_time",
            },
            {
                "issuer": "Chase",
                "product_name": "Freedom Unlimited",
                "account_type": "credit_card",
                "status": "open",
                "opened_date": "2023-08-02",
                "credit_limit": 2500,
                "current_balance": 2025,
                "apr": 28.49,
                "autopay_enabled": False,
                "payment_status": "on_time",
            },
        ],
        "loan_accounts": [
            {
                "lender": "Ally",
                "product_name": "Auto Loan",
                "account_type": "auto_loan",
                "status": "open",
                "opened_date": "2021-11-12",
                "original_balance": 21000,
                "current_balance": 10400,
                "monthly_payment": 412,
                "interest_rate": 6.3,
                "payment_status": "on_time",
            }
        ],
        "inquiries": [
            {
                "creditor": "Chase",
                "inquiry_type": "credit_card",
                "inquiry_date": "2023-08-01",
                "bureau": "Experian",
                "is_hard": True,
            }
        ],
        "payment_history_statuses": ["on_time"] * 6,
    },
    "RECENT_DELINQUENCY_USER": {
        "user": {
            "user_id": "user_003",
            "full_name": "Sofia Ramirez",
            "age": 29,
            "city": "Chicago",
            "state": "IL",
            "occupation": "UX Designer",
            "annual_income": 76000,
        },
        "report": {
            "bureau": "Equifax",
            "score": 611,
            "score_change_30d": -58,
            "summary": "A recent 30-day delinquency materially lowered the score despite moderate utilization and an otherwise manageable file.",
            "score_factors": [
                "A recent delinquency is the largest negative factor",
                "Moderate card balances are adding some pressure",
                "Limited recent inquiries mean payment recovery can help quickly",
            ],
        },
        "credit_accounts": [
            {
                "issuer": "Bank of America",
                "product_name": "Customized Cash",
                "account_type": "credit_card",
                "status": "open",
                "opened_date": "2020-01-14",
                "credit_limit": 6000,
                "current_balance": 1980,
                "apr": 23.49,
                "autopay_enabled": False,
                "payment_status": "late_30",
            },
            {
                "issuer": "Apple Card",
                "product_name": "Titanium",
                "account_type": "credit_card",
                "status": "open",
                "opened_date": "2022-10-03",
                "credit_limit": 4500,
                "current_balance": 1225,
                "apr": 21.99,
                "autopay_enabled": True,
                "payment_status": "on_time",
            },
        ],
        "loan_accounts": [
            {
                "lender": "Nelnet",
                "product_name": "Student Loan",
                "account_type": "student_loan",
                "status": "open",
                "opened_date": "2018-09-01",
                "original_balance": 28000,
                "current_balance": 21400,
                "monthly_payment": 255,
                "interest_rate": 5.2,
                "payment_status": "on_time",
            }
        ],
        "inquiries": [
            {
                "creditor": "Apple Card",
                "inquiry_type": "credit_card",
                "inquiry_date": "2022-09-29",
                "bureau": "Equifax",
                "is_hard": True,
            }
        ],
        "payment_history_statuses": ["on_time", "on_time", "on_time", "late_30", "on_time", "on_time"],
    },
    "THIN_FILE_USER": {
        "user": {
            "user_id": "user_004",
            "full_name": "Noah Patel",
            "age": 24,
            "city": "Seattle",
            "state": "WA",
            "occupation": "Data Analyst",
            "annual_income": 62000,
        },
        "report": {
            "bureau": "TransUnion",
            "score": 689,
            "score_change_30d": 3,
            "summary": "The profile is clean but thin, with short history and only a small number of active tradelines.",
            "score_factors": [
                "Short credit history limits score upside",
                "Very few open accounts make the file thin",
                "Low utilization and clean payments are positives",
            ],
        },
        "credit_accounts": [
            {
                "issuer": "Discover",
                "product_name": "Student Cash Back",
                "account_type": "credit_card",
                "status": "open",
                "opened_date": "2024-02-12",
                "credit_limit": 2000,
                "current_balance": 180,
                "apr": 19.99,
                "autopay_enabled": True,
                "payment_status": "on_time",
            }
        ],
        "loan_accounts": [
            {
                "lender": "FedLoan",
                "product_name": "Student Loan",
                "account_type": "student_loan",
                "status": "open",
                "opened_date": "2023-09-01",
                "original_balance": 12000,
                "current_balance": 11320,
                "monthly_payment": 132,
                "interest_rate": 4.8,
                "payment_status": "on_time",
            }
        ],
        "inquiries": [
            {
                "creditor": "Discover",
                "inquiry_type": "credit_card",
                "inquiry_date": "2024-02-10",
                "bureau": "TransUnion",
                "is_hard": True,
            }
        ],
        "payment_history_statuses": ["on_time"] * 6,
    },
    "CREDIT_HUNGRY_USER": {
        "user": {
            "user_id": "user_005",
            "full_name": "Jasmine Brooks",
            "age": 31,
            "city": "Atlanta",
            "state": "GA",
            "occupation": "Sales Executive",
            "annual_income": 91000,
        },
        "report": {
            "bureau": "Experian",
            "score": 634,
            "score_change_30d": -19,
            "summary": "Multiple recent hard inquiries and newly opened accounts are weighing on an otherwise fair profile.",
            "score_factors": [
                "Many recent hard inquiries signal active credit seeking",
                "Several new accounts reduced average account age",
                "Utilization is manageable but not especially low",
            ],
        },
        "credit_accounts": [
            {
                "issuer": "Chase",
                "product_name": "Freedom Flex",
                "account_type": "credit_card",
                "status": "open",
                "opened_date": "2025-11-15",
                "credit_limit": 3500,
                "current_balance": 910,
                "apr": 25.24,
                "autopay_enabled": True,
                "payment_status": "on_time",
            },
            {
                "issuer": "Capital One",
                "product_name": "SavorOne",
                "account_type": "credit_card",
                "status": "open",
                "opened_date": "2025-09-04",
                "credit_limit": 3000,
                "current_balance": 1230,
                "apr": 27.15,
                "autopay_enabled": False,
                "payment_status": "on_time",
            },
            {
                "issuer": "Amex",
                "product_name": "Everyday",
                "account_type": "credit_card",
                "status": "open",
                "opened_date": "2024-06-21",
                "credit_limit": 5000,
                "current_balance": 910,
                "apr": 21.49,
                "autopay_enabled": True,
                "payment_status": "on_time",
            },
        ],
        "loan_accounts": [
            {
                "lender": "SoFi",
                "product_name": "Personal Loan",
                "account_type": "personal_loan",
                "status": "open",
                "opened_date": "2025-12-01",
                "original_balance": 15000,
                "current_balance": 14120,
                "monthly_payment": 472,
                "interest_rate": 10.2,
                "payment_status": "on_time",
            }
        ],
        "inquiries": [
            {
                "creditor": "Chase",
                "inquiry_type": "credit_card",
                "inquiry_date": "2025-11-12",
                "bureau": "Experian",
                "is_hard": True,
            },
            {
                "creditor": "Capital One",
                "inquiry_type": "credit_card",
                "inquiry_date": "2025-09-02",
                "bureau": "Experian",
                "is_hard": True,
            },
            {
                "creditor": "SoFi",
                "inquiry_type": "personal_loan",
                "inquiry_date": "2025-11-28",
                "bureau": "Experian",
                "is_hard": True,
            },
            {
                "creditor": "Citi",
                "inquiry_type": "credit_card",
                "inquiry_date": "2025-08-14",
                "bureau": "Experian",
                "is_hard": True,
            },
        ],
        "payment_history_statuses": ["on_time"] * 6,
    },
}


PERSONA_ORDER: List[PersonaCode] = [
    "EXCELLENT_PROFILE",
    "HIGH_UTILIZATION_USER",
    "RECENT_DELINQUENCY_USER",
    "THIN_FILE_USER",
    "CREDIT_HUNGRY_USER",
]
